swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
      threshold: 0.7
      interval: 0.3
    right:
      command: 'xdotool key alt+Left'
      threshold: 0.7
      interval: 0.3
    up:
      command: 'bspc desktop -f prev'
      threshold: 0.7
      interval: 0.3
    down:
      command: 'bspc desktop -f next'
      threshold: 0.7
      interval: 0.3
  4:
    left:
      command: 'bspc node -s west'
      threshold: 0.7
      interval: 0.4
    right:
      command: 'bspc node -s east'
      threshold: 0.7
      interval: 0.4
    up:
      command: 'bspc node -s north'
      threshold: 0.7
      interval: 0.4
    down:
      command: 'bspc node -s south'
      threshold: 0.7
      interval: 0.4
pinch:
  2:
    in:
      command: 'xdotool key ctrl+equal'
      threshold: 0.05
      interval: 0.2
    out:
      command: 'xdotool key ctrl+minus'
      threshold: 0.05
      interval: 0.2

      #threshold:
  #swipe: 5
  #pinch: 1

  #interval:
  #swipe: 0.2
  #pinch: 0.1
